### ISSUE TITLE
Harmless yellow error at startup

### ISSUE THREAD

**Issue by C-ljur** [pardeike/VisualExceptions#2]
Launching in a language for which the official translation is incomplete will result in yellow errors. (e.g. italiano, Greek, Dutch)
Log: https://gist.github.com/376fe92ee6f8fcb998fc8fd3e8b98ccb

The mod list when tested is below;
- Harmony
- Visual Exception
- Core
- Royalty
- Ideology
- HugsLib

**Comment by pardeike** [comment]
As you say, harmless…
Known “error” which might get fixed after I took care of all the things that are more important.

**Comment by C-ljur** [comment]
OK, I'm sorry for bothering you!

**Comment by pardeike** [comment]
Nothing to be sorry about. I didn’t mean it like that, it’s more a way to give you short feedback.
